from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys

from . import __version__
from .config import discover_teams, load_team, resolve_team
from .planner import build_plan, render_plan, render_prompt

ROOT = Path.cwd()


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="caw", description="Codex Agent Workshop")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("doctor", help="Check local workshop readiness")

    teams = sub.add_parser("teams", help="List available teams")
    teams.add_argument("action", choices=["list"])

    team = sub.add_parser("team", help="Inspect one team")
    team.add_argument("action", choices=["show"])
    team.add_argument("slug")

    validate = sub.add_parser("validate", help="Validate team definitions")
    validate.add_argument("--team")

    for name in ("plan", "prompt"):
        cmd = sub.add_parser(name)
        cmd.add_argument("--team", default="solo-llc")
        cmd.add_argument("--goal", required=True)
        cmd.add_argument("--mode", choices=["auto", "single", "multi", "symphony"], default="auto")
        if name == "plan":
            cmd.add_argument("--json", action="store_true")

    init = sub.add_parser("init-team", help="Create a starter team definition")
    init.add_argument("slug")
    init.add_argument("--name", required=True)
    init.add_argument("--force", action="store_true")
    return parser


def _doctor(root: Path) -> int:
    checks = {
        "python": sys.version.split()[0],
        "git": shutil.which("git"),
        "codex": shutil.which("codex"),
        "AGENTS.md": (root / "AGENTS.md").exists(),
        "WORKFLOW.md": (root / "WORKFLOW.md").exists(),
        "SPEC.md": (root / "SPEC.md").exists(),
        "teams": len(discover_teams(root)),
    }
    print(json.dumps(checks, indent=2))
    hard_fail = not checks["AGENTS.md"] or not checks["WORKFLOW.md"] or not checks["SPEC.md"] or checks["teams"] == 0
    if checks["codex"] is None:
        print("NOTE: Codex CLI was not found on PATH; planning and prompt generation still work.")
    return 1 if hard_fail else 0


def _validate(root: Path, slug: str | None) -> int:
    paths = discover_teams(root)
    if slug:
        if slug not in paths:
            print(f"ERROR: unknown team {slug!r}", file=sys.stderr)
            return 1
        paths = {slug: paths[slug]}
    errors = 0
    for name, path in paths.items():
        try:
            team = load_team(path)
            print(f"OK {name}: {len(team.roles)} roles")
        except Exception as exc:
            errors += 1
            print(f"ERROR {name}: {exc}", file=sys.stderr)
    if not paths:
        print("ERROR: no teams found", file=sys.stderr)
        return 1
    return 1 if errors else 0


def _starter(slug: str, name: str) -> str:
    return f'''[team]
id = "{slug}"
name = "{name}"
description = "Starter team generated by Codex Agent Workshop."
default_mode = "auto"
max_parallel = 3
max_specialists = 3
final_integrator = "coordinator"
default_reviewer = "reviewer"

[[roles]]
id = "coordinator"
title = "Coordinator"
phase = "plan"
mission = "Clarify the objective, select the smallest useful work plan, integrate results, and surface decisions."
challenge = ["scope creep", "unclear ownership", "unnecessary agent fan-out"]
keywords = ["plan", "strategy", "coordinate", "priority"]
skills = ["orchestrate-team"]
context = ["README.md", "docs/**"]
model_class = "deep"
context_budget_tokens = 16000
handoff_budget_tokens = 1800
risk_ceiling = "medium"
outputs = ["work plan", "integrated handoff"]
always = true

[[roles]]
id = "specialist"
title = "General Specialist"
phase = "work"
mission = "Perform the domain work required by the objective with evidence and a concise handoff."
challenge = ["unsupported assumptions", "missing evidence"]
keywords = ["research", "build", "analyze", "prepare", "draft"]
skills = []
context = []
model_class = "balanced"
context_budget_tokens = 12000
handoff_budget_tokens = 1600
risk_ceiling = "medium"
outputs = ["specialist deliverable"]

[[roles]]
id = "reviewer"
title = "Independent Reviewer"
phase = "review"
mission = "Test the result against evidence, acceptance criteria, risk, and user value."
challenge = ["overconfidence", "missing tests", "unresolved contradictions"]
keywords = ["review", "quality", "verify", "audit"]
skills = []
context = []
model_class = "deep"
context_budget_tokens = 12000
handoff_budget_tokens = 1400
risk_ceiling = "high"
outputs = ["review findings", "readiness verdict"]
always = true
'''


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    root = ROOT

    if args.command == "doctor":
        return _doctor(root)

    if args.command == "teams":
        for slug in discover_teams(root):
            print(slug)
        return 0

    if args.command == "team":
        team = resolve_team(root, args.slug)
        print(json.dumps({
            "id": team.id,
            "name": team.name,
            "description": team.description,
            "roles": [role.id for role in team.roles],
        }, indent=2))
        return 0

    if args.command == "validate":
        return _validate(root, args.team)

    if args.command in {"plan", "prompt"}:
        team = resolve_team(root, args.team)
        plan = build_plan(team, args.goal, mode=args.mode)
        if args.command == "prompt":
            print(render_prompt(plan))
        elif args.json:
            print(json.dumps(plan.to_dict(), indent=2))
        else:
            print(render_plan(plan))
        return 0

    if args.command == "init-team":
        target = root / "teams" / args.slug / "team.toml"
        if target.exists() and not args.force:
            print(f"ERROR: {target} already exists; pass --force to replace it", file=sys.stderr)
            return 1
        if not args.slug or any(ch not in "abcdefghijklmnopqrstuvwxyz0123456789-" for ch in args.slug):
            print("ERROR: slug must use lowercase letters, numbers, and hyphens", file=sys.stderr)
            return 1
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_starter(args.slug, args.name), encoding="utf-8")
        print(target)
        return 0

    return 2
